---
apt_redmine_packages:
  - git
  - ruby-full
  - build-essential
  - python-dev
  - libmysqlclient-dev
  - imagemagick
  - libmagickwand-dev
  - apache2
  - libapache2-mod-passenger
  - mysql-server
  - mysql-client
  - python-pymysql
  - python-mysqldb

app_repo: "https://github.com/redmine/redmine.git"
app_version: 4.1-stable
