- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
- name: restart apache
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: print out
  debug:
    msg: "{{ out.stdout }}"
