all_hosts:
  hosts:
    worker1:
      ansible_host: 192.168.202.7
      ansible_user: tmpuser
    worker2:
      ansible_host: 192.168.202.8
      ansible_user: tmpuser
jump:
  hosts:
    jump_sa:
      ansible_host: 178.124.206.53
