---
- name: Redmine. Install packages
  apt:
    name: "{{ apt_redmine_packages }}"
    state: latest
    update_cache: yes

- name: MySQL. Install and setup
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    mode: 0600
  notify:
    - restart mysql

- meta: flush_handlers

- mysql_db:
    name: "{{ app_db_name }}"
    encoding: utf8

- mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_pass }}"
    priv: "{{ app_db_name }}.*:ALL"
  no_log: "{{ hide_logs | default(True) }}"

- name: Redmine. Clone repository
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_home }}"
    version: "{{ app_version }}"
    accept_hostkey: yes
    update: no

- name: Redmine. Change permissions
  file:
    path: "{{ app_home }}/public"
    owner: www-data
    group: www-data
    recurse: yes

- name: Redmine. Change permissions
  file:
    path: "{{ app_home }}/tmp"
    mode: '777'
    recurse: yes

- name: Config database
  template:
    src: database.yml.j2
    dest: "{{ app_home }}/config/database.yml"
  tags:
    - db::config