---
- name: restart apache
  service:
    name: "{{ 'apache2' if (ansible_os_family == 'Debian') else 'httpd' }}"
    state: restarted
    enabled: yes

- name: stop apache
  service:
    name: "{{ 'apache2' if (ansible_os_family == 'Debian') else 'httpd' }}"
    state: stopped

- name: restart nginx
  service: 
    name: nginx 
    state: restarted

- name: NGINX reload
  service:
    name: nginx
    state: reloaded
