all_hosts:
  hosts:
    centos:
      ansible_host: 192.168.202.11
      ansible_user: root
    ubuntu:
      ansible_host: 192.168.202.12
      ansible_user: root
jump:
  hosts:
    jump_sa:
      ansible_host: 178.124.206.53