---
- name: Deploy to Debian
  include: nginx_ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'

- name: Deploy to RedHat
  include: nginx_redhat.yaml
  when: ansible_distribution == 'CentOS'

- name: Remove default page
  file:
    path: "{{ default_home }}/index.html"
    state: absent

- name: Copy custom first page
  copy:
    src: index.html
    dest: "{{ default_home }}"
  notify:
    - restart nginx

- name: Check connection to localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 3
  register: out

- name: print output
  debug:
    msg: "{{ out }}"

- name: Templates
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Check template
  shell: |
    cat /etc/hosts
  register: out
  changed_when: false

- name: print out
  debug:
    msg: "{{ out.stdout_lines }}"

- name: Check content of the sites
  uri:
    url: "http://{{ item.name }}"
    return_content: yes
  loop: "{{ virtual_hosts }}"
  register: this
  failed_when: "'first custom' not in this.content"
  tags:
  - tests

- name: print out
  debug:
    msg: "{{ this.results[0].content }} | {{ this.results[1].content }}"
  tags:
  - tests

- name: Create sites-available folder for nginx
  become: true
  file:
    path: /etc/nginx/sites-available
    state: directory
  when: ansible_distribution == 'CentOS'

- name: Create sites-enabled folder for nginx
  become: true
  file:
    path: /etc/nginx/sites-enabled
    state: directory
  when: ansible_distribution == 'CentOS'

- name: Creating additional vhost
  become: true
  template:
    src: templates/additionalsite.conf
    dest: "/etc/nginx/sites-available/additionalsite.add.conf"

- name: Enable additional site
  become: true
  file:
    src: "/etc/nginx/sites-available/additionalsite.add.conf"
    dest: "/etc/nginx/sites-enabled/additionalsite.add.conf"
    state: link

- name: Copy custom additional page
  copy:
    src: index.html
    dest: "{{ default_home_additional }}"
  notify:
    - restart nginx

- name: Check connection to additional site on localhost
  wait_for:
    host: "127.0.0.1"
    port: "9001"
    state: started
    timeout: 3
  register: out

- name: print output
  debug:
    msg: "{{ out }}"